### PR TITLE
Publish to Windows Package Manager (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @compose-generator.

### CODE REVIEW

**Comment by marcauberer** [comment]
Already implemented this ourselves. Closing this

**Comment by vedantmgoyal2009** [comment]
I know you've put the package in the automation, but now I'm moving them to my GitHub Action.

**Comment by vedantmgoyal2009** [comment]
I manage winget-pkgs-automation, but since it is getting difficult for me to maintain 1000+ packages, I'm requesting devs to migrate to my action since it's easier to maintain. Hence, I ask you to please switch to action, because I cannot guarantee that every package will be updated by automation.

**Comment by marcauberer** [comment]
Your action does not work with our release workflow. We do not create GitHub releases manually, they are created automatically by another workflow. That means that GitHub will not trigger your workflow.

Feature request: Allow events other than the release event when the action gets the release name as an argument.

**Comment by vedantmgoyal2009** [comment]
Thanks for the idea. Please re-open the PR so that when I can update it and then you can merge :)

**Comment by vedantmgoyal2009** [comment]
@marcauberer I've merged the winget-release step into the existing workflow. Please review and merge. Also, don't forget to:

> 1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
> 2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @spicelang.

**Comment by vedantmgoyal2009** [comment]
@marcauberer the 3 PRs are awaiting your kind attention:
- https://github.com/spicelang/spice/pull/165
- https://github.com/compose-generator/compose-generator/pull/349
- https://github.com/compose-generator/ccom/pull/157

**Review by marcauberer — DISMISSED** [review]

**Comment by marcauberer** [comment]
@vedantmgoyal2009 could you please resolve the merge conflicts? You created the pr against the wrong branch

**Comment by vedantmgoyal2009** [comment]
@marcauberer conflicts have been resolved.

**Review by marcauberer — APPROVED** [review]

**Pull request merged**
